### ISSUE TITLE
Manual help handling

### ISSUE THREAD

**Issue by rafaeldelboni** [nubank/docopt.clj#7]
Hi, first of all, thanks for all your work on this implementation! 

I have a question, given the code example below:

`naval_fate.clj --nonsense`
Returns the usage as expected.

`naval_fate.clj -h` or `naval_fate.clj --help`
This only returns the usage if I uncomment the `(when (arg-map "--help")` or remove the help from usage and options documentation, otherwise, it will execute the `(println arg-map)` 

```clojure
#!/usr/bin/env bb

(require '[babashka.classpath :refer [add-classpath]]
         '[clojure.java.shell :refer [sh]])

(def docopt-dep '{:deps {dev.nubank/docopt {:mvn/version "0.6.1-fix7"}}})
(def cp (:out (sh "clojure" "-Spath" "-Sdeps" (str docopt-dep))))
(add-classpath cp)

(require '[docopt.core :as docopt])

(def usage "Naval Fate.
Usage:
  naval_fate ship new <name>
  naval_fate ship <name> move <lat> <long> [--speed=<kn>]
  naval_fate mine (set|remove) <lat> <long> [--moored|--drifting]
  naval_fate -h | --help
  naval_fate --version
Options:
  -h --help     Show this screen.
  --version     Show version.
  --speed=<kn>  Speed in knots [default: 10].
  --moored      Moored (anchored) mine.
  --drifting    Drifting mine.")

(docopt/docopt
  usage
  *command-line-args*
  (fn [arg-map]
    ;(when (arg-map "--help")
      ;(println usage)
      ;(System/exit 0))
    (println arg-map)))

```

I'm doing something wrong or this manual handling is expected?

**Comment by thiagokokada** [comment]
@rafaeldelboni Sorry about the late response.

Yeah, it is working as expected. What you see with `--nonsense` is that any non-declared option will generate a parse error, that effectively results in the print of all options. Same as `--help` when it is undeclared.

**Comment by rafaeldelboni** [comment]
Hey thanks for your response, that makes a lot of sense :)
